"""
Cross-platform PDF export for token-counter Markdown reports.
"""

from __future__ import annotations

import argparse
from html import escape
from pathlib import Path
from typing import Callable
from urllib.parse import unquote, urlparse

try:
    import markdown as markdown_lib
except ImportError:  # pragma: no cover - exercised via runtime guard
    markdown_lib = None

try:
    from xhtml2pdf import pisa
except ImportError:  # pragma: no cover - exercised via runtime guard
    pisa = None


DEFAULT_PDF_CSS = """
@page {
  size: A4;
  margin: 16mm;
}

body {
  color: #1f2328;
  font-family: Helvetica, Arial, sans-serif;
  font-size: 10.5pt;
  line-height: 1.45;
}

h1, h2, h3, h4, h5, h6 {
  color: #0f172a;
  margin: 18px 0 10px;
}

h1 {
  border-bottom: 2px solid #d0d7de;
  font-size: 20pt;
  padding-bottom: 6px;
}

h2 {
  border-bottom: 1px solid #d0d7de;
  font-size: 14pt;
  padding-bottom: 4px;
}

p, ul, table {
  margin: 0 0 12px;
}

ul {
  padding-left: 20px;
}

code {
  background: #f6f8fa;
  border: 1px solid #d0d7de;
  padding: 1px 4px;
}

table {
  border-collapse: collapse;
  width: 100%;
}

th, td {
  border: 1px solid #d0d7de;
  padding: 6px 8px;
  text-align: left;
  vertical-align: top;
}

th {
  background: #f6f8fa;
  font-weight: bold;
}

img {
  border: 1px solid #d0d7de;
  display: block;
  margin: 10px 0 14px;
  width: 100%;
}

a {
  color: #0969da;
  text-decoration: none;
}
""".strip()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert a token-counter Markdown report to PDF."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to the Markdown report generated by token-counter.",
    )
    parser.add_argument(
        "--output",
        help="Output PDF path. Defaults to the input path with a .pdf suffix.",
    )
    parser.add_argument(
        "--title",
        help="Optional document title override. Defaults to the first H1 heading or file stem.",
    )
    return parser


def _require_pdf_dependencies() -> None:
    missing: list[str] = []
    if markdown_lib is None:
        missing.append("markdown")
    if pisa is None:
        missing.append("xhtml2pdf")
    if missing:
        raise RuntimeError(
            "PDF export requires optional dependencies: "
            + ", ".join(missing)
            + ". Install them with `pip install -e .[pdf]` or `pip install -r requirements.txt`."
        )


def _extract_title(markdown_text: str, fallback: str) -> str:
    for line in markdown_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def _markdown_to_body_html(markdown_text: str) -> str:
    _require_pdf_dependencies()
    assert markdown_lib is not None
    return markdown_lib.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "sane_lists"],
        output_format="html5",
    )


def _build_html_document(title: str, body_html: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <style>
{DEFAULT_PDF_CSS}
  </style>
</head>
<body>
{body_html}
</body>
</html>
"""


def _resolve_asset_uri(uri: str, base_dir: Path) -> str:
    if not uri:
        return uri

    parsed = urlparse(uri)
    if parsed.scheme or uri.startswith("#"):
        return uri

    return str((base_dir / unquote(uri)).resolve())


def _make_link_callback(base_dir: Path) -> Callable[[str, str | None], str]:
    def resolve_link(uri: str, rel: str | None) -> str:
        _ = rel
        return _resolve_asset_uri(uri, base_dir)

    return resolve_link


def export_markdown_report_to_pdf(
    input_path: str | Path,
    output_path: str | Path | None = None,
    *,
    title: str | None = None,
) -> Path:
    _require_pdf_dependencies()

    source = Path(input_path).expanduser().resolve()
    if not source.exists():
        raise FileNotFoundError(f"Markdown report not found: {source}")

    destination = (
        Path(output_path).expanduser().resolve()
        if output_path is not None
        else source.with_suffix(".pdf")
    )
    destination.parent.mkdir(parents=True, exist_ok=True)

    markdown_text = source.read_text(encoding="utf-8")
    document_title = title or _extract_title(markdown_text, source.stem)
    body_html = _markdown_to_body_html(markdown_text)
    html_document = _build_html_document(document_title, body_html)

    assert pisa is not None
    with destination.open("wb") as output_file:
        result = pisa.CreatePDF(
            html_document,
            dest=output_file,
            encoding="utf-8",
            link_callback=_make_link_callback(source.parent),
        )

    if result.err:
        destination.unlink(missing_ok=True)
        raise RuntimeError(f"Failed to render PDF from Markdown report: {source}")

    return destination


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    output_path = export_markdown_report_to_pdf(
        args.input,
        args.output,
        title=args.title,
    )
    print(f"PDF written to: {output_path}")


if __name__ == "__main__":
    main()
